services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/overherd/src
    command: ["cargo", "run"]
    networks:
      - p2p-network
    environment:
      - RUST_LOG=info
    deploy:
      replicas: 5
    init: true

networks:
  p2p-network:
    driver: bridge
