services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/overherd/src
      - ./scripts/web_view/out:/overherd/output
    networks:
      - p2p-network
    environment:
      - RUST_LOG=info
    deploy:
      replicas: 10
    init: true

networks:
  p2p-network:
    driver: bridge
