# Devolopment Dockerfile to use in docker-compose.yml

FROM rust:1.92.0-alpine

WORKDIR /overherd

RUN apk add curl

COPY Cargo.toml Cargo.lock ./
# Force dependency installation before in order to cache it before
RUN mkdir src \
    && touch src/lib.rs \
    && cargo build

COPY config.toml /root/.config/overheard/
COPY src/ ./src
RUN cargo build

COPY entrypoint.sh ./entrypoint.sh
ENTRYPOINT ["/overherd/entrypoint.sh"]

CMD ["/overherd/target/debug/overherd"]
