# vim: set fenc=utf-8 ft=taskini:
# see: https://github.com/skywind3000/asynctasks.vim/wiki/Task-Config

[run]
command=OVERHEARD_CONFIG_PATH="./config.toml" cargo run
output=terminal
errorformat=%f:%l:%m

[build]
command=cargo build
output=terminal
errorformat=%f:%l:%m

[docker-compose]
command=docker compose up
output=terminal
errorformat=%f:%l:%m

